server:
  port: 8080

spring:
  application:
    name: novel-cast-server
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 101MB
  mvc:
    async:
      request-timeout: 600000
  ai:
    retry:
      max-attempts: 1
    openai:
      base-url: https://api-inference.modelscope.cn
      api-key: ${MODELSCOPE_APIKEY:666}
      chat:
        options:
          model: ${MODELSCOPE_MODEL:Qwen/Qwen3-30B-A3B-Instruct-2507}
          temperature: 0.7
          max-tokens: 20000

novel-cast:
  file-system-path:
  gpt-so-vits-url: 'http://127.0.0.1:23452'
  remote-speech-path:
  remote-gsv-model-path:
  gsv:
    type: base # 'base', 'fast-inference' fast-inference api 支持改变模型
    cut: cut0 # fast-inference 的参数
